# Generated by Django 4.1.5 on 2023-02-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpCode', models.CharField(max_length=20)),
                ('EmpName', models.CharField(max_length=100)),
                ('EmpGrade', models.CharField(max_length=50)),
                ('EmpRole', models.CharField(max_length=100)),
                ('EmpLocation', models.CharField(max_length=100)),
                ('EmpBilled', models.CharField(max_length=100)),
                ('EmpStatus', models.CharField(max_length=100)),
            ],
        ),
    ]
